### ISSUE TITLE
Create smart contract upon successful song upload 

### ISSUE THREAD

**Issue by ann0605** [nyu-software-engineering/music-through-blockchain#46]
Smart contract should be created once the song information is saved in the database.
This task is part of User Story #4

**Comment by Nlopierre** [comment]
I managed to do something better than creating a new contract per song. I have a unique contract that has includes royalties and song sales functionality for EVERY song. This means that the song only needs to be registered in it by using an address. So instead of creating a contract, we simply create a "wallet" for the song. Web3 allows us to do this by making a simple API call that returns a JSON file with the public address and private key. So we can simply give this to the user to plug in MetaMask to handle their transactions, and all we need to do is handle is what the user wants to do with it (withdraw, sell royalities, buy royalties, etc). Now all we need to do is test the contracts a bit more and start plugging web3 in our React components.
